// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DxtCoalRoaT1s-wc8mt-QJH5pQDqciU',
    appId: '1:760512575032:web:41f3c7c4fa249bd597d8cd',
    messagingSenderId: '760512575032',
    projectId: 'subloop-pinaka-2026',
    authDomain: 'subloop-pinaka-2026.firebaseapp.com',
    storageBucket: 'subloop-pinaka-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvV3khUdUFoBlug6BGJ5BVj1MhMfvrQ1Q',
    appId: '1:760512575032:android:de269faa5480366697d8cd',
    messagingSenderId: '760512575032',
    projectId: 'subloop-pinaka-2026',
    storageBucket: 'subloop-pinaka-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9A0cabuSexNw99kZSCPqORp3qE-9HzpQ',
    appId: '1:760512575032:ios:b40bf143c155ea3897d8cd',
    messagingSenderId: '760512575032',
    projectId: 'subloop-pinaka-2026',
    storageBucket: 'subloop-pinaka-2026.firebasestorage.app',
    iosBundleId: 'com.example.subloop',
  );
}
